### ISSUE TITLE
speed-transition.lua

### ISSUE THREAD

**Issue by oltodosel** [zenyd/mpv-scripts#10]
There's also additional sub colorization that you might should hide at `toggle_sub_visibility`.

```
    sub_color3 = mp.get_property("sub-shadow-color", "0/0/0/1")
    mp.set_property("sub-shadow-color", "0/0/0/0")
else
    mp.set_property("sub-shadow-color", sub_color3)
```

P.S.
Nice script.

**Comment by bitingsock** [comment]
I have been unable to contact zenyd in over a year, hopefully he has time to get back to this at sometime. If you want in the mean time you can use my temporary version that includes this fix and an avdesync.
https://gist.github.com/bitingsock/bf739ecc6502edded3570cb8d309d1c2

**Comment by zenyd** [comment]
Hi sorry for the delay! It's been merged.
