### ISSUE TITLE
Speedup-Transition - How can I enable this ON by default (not have to hit Ctrl+J?)

### ISSUE THREAD

**Issue by EliCodesForFun** [zenyd/mpv-scripts#22]
Hello,

I was wondering how I can enable this add-on to automatically be on (as if I had pressed Ctrl+J upon startup).
I've been trying to figure this out in via a .conf file or by editing the addon, I'm just kinda dumb on this.

Thanks,
Vlad

***EDIT***
I figured it out. I simply added this to the very bottom of the script:

toggle()

This makes it so that the toggle command is run on startup, after the hotkey commands have been created for mpv.toggle()

**Comment by zenyd** [comment]
Or put `toggle()` at the end of `reset_on_file_load()` should also work.
