### ISSUE TITLE
speed-transition.lua: Suggestion for youtube generated subtitles (minimum subtitle length forced skip)

### ISSUE THREAD

**Issue by Reinbowsaur** [zenyd/mpv-scripts#28]
Youtube generates subtitles but they are useless with this plugin unfortunately to the way they are generated, each line of subtitle will be shown until the next line is generated leaving no gaps for this plugin to skip through.

This could be solved by implementing an option that will fast foward automatically after a subtitle has being showing for a certain amount of seconds.

An option for example might be useful to call it "forcedLookAhead = x" (After a subtitle has being showing for x seconds it will forcefully speed up to the next subtitle) this is because with youtube the talker has likely already finished, while the subtitles generated by youtube will continue to show forever until it generates more subtitles, leaving massive gaps of silence, that could be skipped if detected showing too long.

**Comment by chapmanjacobd** [comment]
Yes. I have encountered subtitles from many sources (not just YouTube ones) that have this issue. A `max_duration` or `subtitle_timeout` setting should fix this.

**Comment by chapmanjacobd** [comment]
I added this functionality to the Ben Kerman sub-skip script https://github.com/chapmanjacobd/computer/commit/c11721d2a48f34ad849fa513e9e3a91d34f9ff32 

it feels a bit hacky but it is working for me :)

**Comment by chapmanjacobd** [comment]
There were quite a few bugs but I've ironed them out: 

https://github.com/chapmanjacobd/computer/blob/main/.config/mpv/scripts/sub-skip.lua

**Comment by zenyd** [comment]
This is implemented as of 9bdce0050144cb24f92475f7bdd77180e0e4c26b
