### ISSUE TITLE
Is it possible to make delete_file script remove file to recycle bin instead of permanently deleting the file?

### ISSUE THREAD

**Issue by TheLongLife** [zenyd/mpv-scripts#29]

**Comment by Obegg** [comment]
I don't want to delete it permanently, only to the recycle bin.

**Comment by zenyd** [comment]
Not exactly the recycle bin (don't think that's easy to do), but possible to move into other folder as of 885b9bd0563086feaf977a0ba12752d6f837dcf9

**Comment by Geniusssmit** [comment]
Script is not wirking for me on win 10. Nothing happens after quiting mpv. What should I do?

**Comment by Geniusssmit** [comment]
oh I got it, it's not working if folders have cyrillic letters in it

**Comment by Geniusssmit** [comment]
how can I change folder to for example "G:\1" ?

**Comment by zenyd** [comment]
make a `delete_file.conf` inside of `script-opts` with contents:
```
MoveToFolder=yes
DeletedFilesPath=G:\1
```
