### ISSUE TITLE
Please explain how to apply and install censor script like I am 5.

### ISSUE THREAD

**Issue by alookaAchaar** [zenyd/mpv-scripts#30]
It's my humble request as I want to censor some anime and I am new to this mpv script thing . I will be grateful if u explain me . As time stamps format is confusing me and it didn't worked when I tried.

Please give another example

**Comment by zenyd** [comment]
ok so imagine you want to skip the intro which begins on timestamp `0:2:30` and lasts until timestamp `0:4:00`
your anime is called `Attack on Titan - 03.mkv`.
So you create a text file named `Attack on Titan - 03.txt` inside the `names` folder.
Now open the just created file and paste `0:02:30 0:04:00` inside it. Save and exit.
If you open the anime `Attack on Titan - 03.mkv` it should now skip to the timestamp `0:04:00` after the playtime reaches `0:02:30`.
If you now also wanted to skip the ending you would add one more line to the text file with contents like this `0:21:00 0:22:00`.

For (anime) series you would have to create a text file for every episode which will likely be cumbersome... There is no wildcard support yet.

If you want to test if the script works select a video file and follow the steps above. Skip a couple of seconds before the first timestamp in the file and you should notice it skipping to the second timestamp, when it reaches the first one.

If it still doesn't work we need to troubleshoot some more.

**Comment by alookaAchaar** [comment]
> ok so imagine you want to skip the intro which begins on timestamp `0:2:30` and lasts until timestamp `0:4:00`
> your anime is called `Attack on Titan - 03.mkv`.
> So you create a text file named `Attack on Titan - 03.txt` inside the `names` folder.
> Now open the just created file and paste `0:02:30 0:04:00` inside it. Save and exit.
> If you open the anime `Attack on Titan - 03.mkv` it should now skip to the timestamp `0:04:00` after the playtime reaches `0:02:30`.
> If you now also wanted to skip the ending you would add one more line to the text file with contents like this `0:21:00 0:22:00`.
> 
> For (anime) series you would have to create a text file for every episode which will likely be cumbersome... There is no wildcard support yet.
> 
> If you want to test if the script works select a video file and follow the steps above. Skip a couple of seconds before the first timestamp in the file and you should notice it skipping to the second timestamp, when it reaches the first one.
> 
> If it still doesn't work we need to troubleshoot some more.

Thank you very much you really helped it a lot even though you are doing it for free. You are such a inspiration for me to learn coding. I thought u would never reply.

Thanks again . It works .
