### ISSUE TITLE
Proposal of improvements

### ISSUE THREAD

**Issue by jimmy-1000** [zenyd/mpv-scripts#31]
1.  Delete immediately the file, don't wait until closing mpv.
2.  Send the file to recycle bin, don't kill permanently the file.
3. Support non-English characters (because it doesn't work with files written in other languages and symbols)

**Comment by zenyd** [comment]
1. Would probably interfere with playlists
2. Not in recycle bin, but into a folder in the user profile is implemented in 885b9bd0563086feaf977a0ba12752d6f837dcf9
3. Can't reproduce this

**Comment by jimmy-1000** [comment]
> 1. Would probably interfere with playlists
> 
>     2. Not in recycle bin, but into a folder in the user profile is implemented in [885b9bd](https://github.com/zenyd/mpv-scripts/commit/885b9bd0563086feaf977a0ba12752d6f837dcf9)
> 
>     3. Can't reproduce this

1. I have done some tests, mpv "thinks" something happens, but it plays all the remaining videos with any problem.
2. I know "send to recycle bin" is difficult to program, but it's the right way.
3. No?? Rename your videos with non-English languages, for example: Spanish árbol, French château, Russian кровать.

**Comment by zenyd** [comment]
3. I'm on Windows 11 and tried with your examples and it works for me. In another post of yours you said you're using Windows 7? Maybe it doesn't work properly on that OS.

**Comment by jimmy-1000** [comment]
> 3. I'm on Windows 11 and tried with your examples and it works for me. In another post of yours you said you're using Windows 7? Maybe it doesn't work properly on that OS.

Ohhh, but using CLI I can delete any files using **del** command, lua script works different.

**Comment by zenyd** [comment]
Can you try again with the attached script (obviously change extension to lua)?
[delete_file.lua.txt](https://github.com/zenyd/mpv-scripts/files/8547018/delete_file.lua.txt)

**Comment by jimmy-1000** [comment]
> Can you try again with the attached script (obviously change extension to lua)? This calls the `del` command to delete the file. [delete_file.lua.txt](https://github.com/zenyd/mpv-scripts/files/8547018/delete_file.lua.txt)

Sadly doesn't work. When mpv closes, console says "System cannot find the specified path"

**Comment by dyphire** [comment]
Maybe can refer to this script of [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/src/delete-current-file.lua) , which implements these functions.

**Comment by jimmy-1000** [comment]
> Maybe can refer to this script of [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/src/delete-current-file.lua) , which implements these functions.

Interesting, I'm going to try it, thanks!

**Comment by jimmy-1000** [comment]
> Maybe can refer to this script of [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/src/delete-current-file.lua) , which implements these functions.

Interesting, I'm going to try it, thanks 👌

**Comment by jimmy-1000** [comment]
> Maybe can refer to this script of [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/src/delete-current-file.lua) , which implements these functions.

It works perfect, thanks 👌
