### ISSUE TITLE
[feature request] delete-file: add an option to delete empty folders

### ISSUE THREAD

**Issue by ghost** [zenyd/mpv-scripts#48]
The current version of the delete script only removes files, any orphan directories are left behind. An option to delete the leftover empty folders would be welcomed by many, I'm sure.

Perhaps disabled by default. Should likely have a whitelist to avoid the removal of system directories (e.g. `~/Videos` and `~/Music` on Gnome).

**Comment by zenyd** [comment]
As you said this might be dangerous, so I rather not include this. But this could easily be implemented with  a batch file.
