### ISSUE TITLE
delete_file movetofolder not moving to specified folder

### ISSUE THREAD

**Issue by Dutchlikeme** [zenyd/mpv-scripts#50]
Hi, I've got a delete_file.conf made, with 

`MoveToFolder=yes`
`DeletedFilesPath=C:\Users\*****\Videos\Deleted`

It doesn't move them there, it moves them to the standard 
`C:\Users\*****\delete_file`

Where else would I specify the path for the deleted files? I've tried in 

`options = {}`
`options.MoveToFolder = true`
`options.DeletedFilesPath = "C:\Users\*****\Videos\Deleted"`

or

`if package.config:sub(1,1) == "/" then`
`   options.DeletedFilesPath = utils.join_path(os.getenv("HOME"), "delete_file")`
`   ops = "unix"`
`else`
`   options.DeletedFilesPath = utils.join_path(os.getenv("USERPROFILE"), "delete_file")`
`   ops = "win"`
`end`

But changing this code causes the script not to work at all (no CTRL + DEL "deleting current file"

**Comment by zenyd** [comment]
First restore the made changes then put this  `print(utils.to_string(options))` after the line `read_options(options)`. Now launch mpv from the command line and try to delete some files and look for output in the terminal window.

**Comment by Dutchlikeme** [comment]
I'm not sure what to do exactly, buy I've redownloaded your script and put `print(utils.to_string(options))` after the line you said, when opening mpv it says
[delete_file_backup] {"DeletedFilesPath" = "C:\Users\*****/delete_file", "MoveToFolder" = true}

I tried adding `print(options.DeletedFilesPath)` and the path doesn't change when I edit any of these

if package.config:sub(1,1) == "/" then
   options.DeletedFilesPath = utils.join_path(os.getenv("HOME"), "delete_file\test")
   ops = "unix"
else
   options.DeletedFilesPath = utils.join_path(os.getenv("USERPROFILE"), "delete_file\test")
   ops = "win"
end

I'm going to reread the manual

**Comment by zenyd** [comment]
Where did you put your delete_file.conf?

**Comment by Dutchlikeme** [comment]
My MPV is installed here
`C:\Users\*****\AppData\Roaming\mpv`
My delete_file.lua is here
`C:\Users\*****\AppData\Roaming\mpv\scripts`
My delete_file.conf is here
`C:\Users\*****\AppData\Roaming\mpv\scripts-opts`

I really hope I haven't misnamed the scripts-opts folder

**Comment by zenyd** [comment]
you did :) it should be script-opts

**Comment by Dutchlikeme** [comment]
Thank you very much for the script and help!
