### ISSUE TITLE
[delete-file] No marked files are deleted when EOF is reached

### ISSUE THREAD

**Issue by aeph6Ee0** [zenyd/mpv-scripts#9]
Currently, files are only deleted when mpv is closed by the user.
However, if a user marks a file for deletion but plays it back to the end, the file will not be deleted.
This is a bit unintuitive.

My usecase for this script is to play a bunch of files and delete some of them on the fly (if I don't like them). At the end of the playlist, all marked files should be deleted (which is currently not the case).

In order to fix this, I suggest to add `or e.reason == "eof"` in the following line:
https://github.com/zenyd/mpv-scripts/blob/4c023ed7eaeff6176f4a14bee9f34228c279999a/delete_file.lua#L33

**Comment by 20NE** [comment]
same issue.
The fix works, good job!

**Comment by dumbledore** [comment]
See https://github.com/zenyd/mpv-scripts/pull/11

**Comment by zenyd** [comment]
Can you please check if the latest #11 (merged) fixes your issue?

**Comment by aeph6Ee0** [comment]
Yes, it does fix my issue. Thanks.
